#!/usr/bin/env python3

import json
import locale
import sys
import operator
import reports
import emails
import pandas as pd

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data



def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])

def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  most_sales = {"total_sales": 0}
  sales_by_year = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    if item["total_sales"] > most_sales["total_sales"]:
        most_sales = item
    # TODO: also handle most popular car_year
    if item['car']['car_year'] not in sales_by_year:
        sales_by_year[item['car']['car_year']] = int(item['total_sales'])
    else:
        sales_by_year[item['car']['car_year']] += int(item['total_sales'])

  sorted_sales_by_year = sorted(sales_by_year.items(), key=operator.itemgetter(1))
  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(format_car(most_sales["car"]), most_sales["total_sales"]),
    "The most popular year was {} with {} sales.".format(sorted_sales_by_year[-1][0], sorted_sales_by_year[-1][1])
  ]

  return summary

def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data

def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  df = pd.read_json("car_sales.json")
  df = df.sort_values(by=['total_sales'], ascending=False)
  print(df['car'])
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report

  cars_data = cars_dict_to_table(data)

  pdf_summary = []
  reports.generate('/tmp/cars.pdf','Sales summary for last month', "<br/>".join(summary) , cars_data)
  # TODO: send the PDF report as an email attachment
  sender = 'automation@example.com'
  recipient = 'student-01-f3ca5d8d5514'
  subject = 'Sales summary for last month'
  body = '\n'.join(summary)
  attachment_path = '/tmp/cars.pdf'
  print(body)
  email = emails.generate(sender,recipient, subject, body, attachment_path)
  #emails.send(email)

if __name__ == "__main__":
  main(sys.argv)